set-option global grepcmd 'ag --column'
add-highlighter global/ show-matching

hook global WinCreate ^[^*]+$ %{ add-highlighter window/ number-lines -hlcursor }

map global normal <c-p> ': fzf-mode<ret>'

declare-option -hidden regex curword
set-face global CurWord default,rgb:4a4a4a

hook global NormalIdle .* %{
    eval -draft %{ try %{
        exec <space><a-i>w <a-k>\A\w+\z<ret>
        set-option buffer curword "\b\Q%val{selection}\E\b"
    } catch %{
        set-option buffer curword ''
    } }
}

add-highlighter global/ dynregex '%opt{curword}' 0:CurWord

map global user -docstring 'paste (after) from clipboard' p '!%s<ret>' 'xclip -o'
map global user -docstring 'paste (before) from clipboard' P '<a-!>%s<ret>' 'xclip -o'
map global user -docstring 'yank to clipboard' y '<a-|>%s<ret>:echo -markup %%{{Information}copied selection to X11 clipboard}<ret>' 'xclip -i'
map global user -docstring 'replace from clipboard' R '|%s<ret>' 'xclip -o'

define-command mkdir %{ nop %sh{ mkdir -p $(dirname $kak_buffile) } }

hook global WinSetOption filetype=elm %{
  set window formatcmd 'elm-format --stdin'
}

map global normal <space> , -docstring 'leader'
map global normal <backspace> <space> -docstring 'remove all sels except main'
map global normal <a-backspace> <a-space> -docstring 'remove main sel'    
map global normal '#' :comment-line<ret>      
